# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoMenu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_name',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='fri_close_time',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='fri_open_time',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='header_image',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mon_close_time',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mon_open_time',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sat_close_time',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sat_open_time',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sun_close_time',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sun_open_time',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thu_close_time',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thu_open_time',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tue_close_time',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tue_open_time',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wed_close_time',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wed_open_time',
            field=models.ImageField(default=datetime.time(0, 1), upload_to=b''),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotoMenu.Restaurant'),
        ),
    ]
