# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 18:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoMenu', '0002_auto_20160619_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='fri_close_time',
            field=models.TimeField(default=datetime.time(0, 1)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='fri_open_time',
            field=models.TimeField(default=datetime.time(0, 1)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='header_image',
            field=models.ImageField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='mon_close_time',
            field=models.TimeField(default=datetime.time(0, 1)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='mon_open_time',
            field=models.TimeField(default=datetime.time(0, 1)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sat_close_time',
            field=models.TimeField(default=datetime.time(0, 1)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sat_open_time',
            field=models.TimeField(default=datetime.time(0, 1)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sun_close_time',
            field=models.TimeField(default=datetime.time(0, 1)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sun_open_time',
            field=models.TimeField(default=datetime.time(0, 1)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='thu_close_time',
            field=models.TimeField(default=datetime.time(0, 1)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='thu_open_time',
            field=models.TimeField(default=datetime.time(0, 1)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tue_close_time',
            field=models.TimeField(default=datetime.time(0, 1)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tue_open_time',
            field=models.TimeField(default=datetime.time(0, 1)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='wed_close_time',
            field=models.TimeField(default=datetime.time(0, 1)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='wed_open_time',
            field=models.TimeField(default=datetime.time(0, 1)),
        ),
    ]
