# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoMenu', '0003_auto_20160622_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='is_header_section',
            field=models.BooleanField(),
        ),
    ]
