# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 16:46
from __future__ import unicode_literals

import PhotoMenu.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoMenu', '0003_auto_20160619_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='food_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(upload_to=PhotoMenu.models.get_food_upload_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='header_image',
            field=models.ImageField(upload_to=PhotoMenu.models.get_restaurant_upload_path),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='menu_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PhotoMenu.MenuCategory'),
        ),
    ]
