# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoMenu', '0004_auto_20160622_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='is_header_section',
        ),
    ]
