# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoMenu', '0004_auto_20160620_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='menu_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotoMenu.MenuCategory'),
        ),
    ]
