# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoMenu', '0005_remove_menucategory_is_header_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
