# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoMenu', '0005_auto_20160620_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name_plural': 'Menu categories'},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PhotoMenu.Restaurant'),
            preserve_default=False,
        ),
    ]
