# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoMenu', '0007_auto_20160620_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='restaurant',
        ),
    ]
