# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoMenu', '0008_remove_fooditem_restaurant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItem',
            new_name='MenuItem',
        ),
    ]
